apps/adminstore/urls.py
from django.urls import path

from apps.adminstore import views




app_name = 'adminstore'


urlpatterns = [
    path('', views.Metrics.as_view(), name='metrics'),
    path('brands/', views.ManageBrand.as_view(), name='brands'),
    path('categories/', views.ManageCategory.as_view(), name='categories'),
    path('company/', views.ManageCompany.as_view(), name='company'),
    path('discounts/', views.ManageDiscount.as_view(), name='discounts'),
    path('orders/', views.ManageOrder.as_view(), name='orders'),
    path('products/', views.ManageProduct.as_view(), name='products'),
    path('users/', views.ManageUser.as_view(), name='users'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path




urlpatterns = [
    path('', include('apps.accounts.urls')),
    path('', include('apps.shop.urls')),
    path('', include('apps.utils.urls')),
    path('admin-store/', include('apps.adminstore.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/adminstore/views/ManageBrand.py
from django.contrib import messages
from django.contrib.auth.mixins import UserPassesTestMixin
from django.core.paginator import Paginator, EmptyPage
from django.db.models import Q
from django.shortcuts import redirect, render
from django.views import View

from apps.shop.models import Brand




class ManageBrand(UserPassesTestMixin, View):
    """
    Gestiona las marcas disponibles en la tienda virtual.
    """
    http_method_names = ['get', 'post', 'put', 'delete']


    def test_func(self):
        """
        Solamente están autorizados a acceder a esta página los
        usuarios con el atributo is_staff=True.
        """
        return self.request.user.is_staff


    def handle_no_permission(self):
        """
        Si un usuario tiene acceso denegado, se redirecciona al inicio.
        """
        messages.warning(self.request, '¡Acceso denegado!')
        return redirect('shop:home')


    def dispatch(self, *args, **kwargs):
        """
        Maneja las solicitudes PUT y DELETE a través de un campo
        <input type="hidden" name="_method" value="put|delete">
        debido a que los formulario HTML solo permiten GET o POST.
        """
        method = self.request.POST.get('_method', '').lower()
        if method == 'put':
            return self.put(*args, **kwargs)
        if method == 'delete':
            return self.delete(*args, **kwargs)
        return super(ManageBrand, self).dispatch(*args, **kwargs)


    def get(self, request):
        """
        Muestra la tabla con las marcas existentes en la base de datos.
        """
        # Obtenemos todas las marcas.
        brands = Brand.objects.filter(is_active=True).order_by('pk')

        # Obtenemos el valor del cuadro de búsqueda.
        query = request.GET.get('q')

        # Si se ingresó algo en el cuadro de búsqueda, se filtran las marcas.
        if query:
            brands = brands.filter(
                Q(name__icontains=query)
            )

        # Creamos el objeto paginador.
        obj_per_page = 25
        paginator = Paginator(brands, obj_per_page)
        num_page = request.GET.get('page')

        try:
            page = paginator.get_page(num_page)
        except EmptyPage:
            # Si la URL no tiene ?page= devuelve la primera página.
            page = paginator.get_page(1)

        context = {
            'brands': brands,
            'page': page,
        }

        return render(request, 'adminstore/brand/show_brands.html', context)


    def post(self, request):
        """
        Agrega una nueva marca a la base de datos.
        """
        # Obtenemos los datos del formulario.
        name = request.POST.get('name')

        # Creamos el registro en la base de datos.
        Brand.objects.create(
            name=name,
        )

        # Redirigimos a la misma página de gestión de marcas.
        messages.success(request, '¡Haz agregado una nueva marca!')
        return redirect('adminstore:brands')


    def put(self, request):
        """
        Actualiza una marca en la base de datos.
        """
        # Obtenemos los datos del formulario.
        brand_id = request.POST['id']
        name = request.POST['name']

        # Obtenemos la marca de la base de datos.
        brand = Brand.objects.get(pk=brand_id)

        # Actualizamos el registro.
        brand.name = name
        brand.save()

        # Redirigimos a la misma página de gestión de marcas.
        messages.success(request, '¡Haz modificado una marca!')
        return redirect('adminstore:brands')


    def delete(self, request):
        """
        Elimina una marca de la base de datos.
        """
        # Obtenemos los datos del formulario.
        brand_id = request.POST['id']

        # Obtenemos la marca de la base de datos.
        brand = Brand.objects.get(pk=brand_id)

        # Actualizamos el registro.
        brand.is_active = False
        brand.save()

        # Redirigimos a la misma página de gestión de marcas.
        messages.warning(request, '¡Haz eliminado una marca!')
        return redirect('adminstore:brands')

apps/adminstore/views/ManageCategory.py
from django.contrib import messages
from django.contrib.auth.mixins import UserPassesTestMixin
from django.core.paginator import Paginator, EmptyPage
from django.db.models import Q
from django.shortcuts import redirect, render
from django.views import View

from apps.shop.models import Category




class ManageCategory(UserPassesTestMixin, View):
    """
    Gestiona las categorías disponibles en la tienda virtual.
    """
    http_method_names = ['get', 'post', 'put', 'delete']


    def test_func(self):
        """
        Solamente están autorizados a acceder a esta página los
        usuarios con el atributo is_staff=True.
        """
        return self.request.user.is_staff


    def handle_no_permission(self):
        """
        Si un usuario tiene acceso denegado, se redirecciona al inicio.
        """
        messages.warning(self.request, '¡Acceso denegado!')
        return redirect('shop:home')


    def dispatch(self, *args, **kwargs):
        """
        Maneja las solicitudes PUT y DELETE a través de un campo
        <input type="hidden" name="_method" value="put|delete">
        debido a que los formulario HTML solo permiten GET o POST.
        """
        method = self.request.POST.get('_method', '').lower()
        if method == 'put':
            return self.put(*args, **kwargs)
        if method == 'delete':
            return self.delete(*args, **kwargs)
        return super(ManageCategory, self).dispatch(*args, **kwargs)


    def get(self, request):
        """
        Muestra la tabla con las categorías existentes en la base de datos.
        """
        # Obtenemos todas las categorías.
        categories = Category.objects.filter(is_active=True).order_by('pk')

        # Obtenemos el valor del cuadro de búsqueda.
        query = request.GET.get('q')

        # Si se ingresó algo en el cuadro de búsqueda, se filtran las categorías.
        if query:
            categories = categories.filter(
                Q(name__icontains=query)
            )

        # Creamos el objeto paginador.
        obj_per_page = 25
        paginator = Paginator(categories, obj_per_page)
        num_page = request.GET.get('page')

        try:
            page = paginator.get_page(num_page)
        except EmptyPage:
            # Si la URL no tiene ?page= devuelve la primera página.
            page = paginator.get_page(1)

        context = {
            'categories': categories,
            'page': page,
        }

        return render(request, 'adminstore/category/show.html', context)


    def post(self, request):
        """
        Agrega una nueva categoría a la base de datos.
        """
        # Obtenemos los datos del formulario.
        name = request.POST.get('name')

        # Creamos el registro en la base de datos.
        Category.objects.create(
            name=name,
        )

        # Redirigimos a la misma página de gestión de categorías.
        messages.success(request, '¡Haz agregado una nueva categoría!')
        return redirect('adminstore:categories')


    def put(self, request):
        """
        Actualiza una categoría en la base de datos.
        """
        # Obtenemos los datos del formulario.
        category_id = request.POST['id']
        name = request.POST['name']

        # Obtenemos la categoría de la base de datos.
        category = Category.objects.get(pk=category_id)

        # Actualizamos el registro.
        category.name = name
        category.save()

        # Redirigimos a la misma página de gestión de categoría.
        messages.success(request, '¡Haz modificado una categoría!')
        return redirect('adminstore:categories')


    def delete(self, request):
        """
        Elimina una categoría de la base de datos.
        """
        # Obtenemos los datos del formulario.
        category_id = request.POST['id']

        # Obtenemos la marca de la base de datos.
        category = Category.objects.get(pk=category_id)

        # Actualizamos el registro.
        category.is_active = False
        category.save()

        # Redirigimos a la misma página de gestión de categorías.
        messages.warning(request, '¡Haz eliminado una categoría!')
        return redirect('adminstore:categories')

apps/adminstore/views/ManageCompany.py
from django.contrib import messages
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import redirect, render
from django.views import View

from apps.shop.models import Company




class ManageCompany(UserPassesTestMixin, View):
    """
    Gestiona la información de la tienda virtual.
    """
    http_method_names = ['get', 'post', 'put']


    def test_func(self):
        """
        Solamente están autorizados a acceder a esta página los
        usuarios con el atributo is_staff=True.
        """
        return self.request.user.is_staff


    def handle_no_permission(self):
        """
        Si un usuario tiene acceso denegado, se redirecciona al inicio.
        """
        messages.warning(self.request, '¡Acceso denegado!')
        return redirect('shop:home')


    def dispatch(self, *args, **kwargs):
        """
        Maneja las solicitudes PUT y DELETE a través de un campo
        <input type="hidden" name="_method" value="put|delete">
        debido a que los formulario HTML solo permiten GET o POST.
        """
        method = self.request.POST.get('_method', '').lower()
        if method == 'put':
            return self.put(*args, **kwargs)
        if method == 'delete':
            return self.delete(*args, **kwargs)
        return super(ManageCompany, self).dispatch(*args, **kwargs)


    def get(self, request):
        """
        Muestra la información de la tienda en la base de datos.
        """
        # Obtenemos la información de la tienda.
        company = Company.objects.filter(is_active=True).first()

        context = {
            'company': company,
        }

        return render(request, 'adminstore/company/show.html', context)


    def post(self, request):
        """
        Agrega la información de la tienda en la base de datos.
        """
        # Obtenemos los datos del formulario.
        rut = request.POST['rut']
        name = request.POST['name']
        address = request.POST['address']
        phone = request.POST['phone']
        email = request.POST['email']
        schedule = request.POST['schedule']

        # Creamos el registro de la base de datos.
        Company.objects.create(
            rut=rut,
            name=name,
            address=address,
            phone=phone,
            email=email,
            schedule=schedule
        )

        # Redirigimos a la misma página de gestión de marcas.
        messages.success(request, '¡Haz agregado la información de la tienda!')
        return redirect('adminstore:company')


    def put(self, request):
        """
        Actualiza la información de la tienda en la base de datos.
        """
        # Obtenemos los datos del formulario.
        company_id = request.POST['id']
        rut = request.POST['rut']
        name = request.POST['name']
        address = request.POST['address']
        phone = request.POST['phone']
        email = request.POST['email']
        schedule = request.POST['schedule']

        # Obtenemos el registro de la base de datos.
        company = Company.objects.get(pk=company_id)

        # Actualizamos el registro.
        company.rut = rut
        company.name = name
        company.address = address
        company.phone = phone
        company.email = email
        company.schedule = schedule
        company.save()

        # Redirigimos a la misma página de gestión de marcas.
        messages.success(request, '¡Haz modificado la información de la tienda!')
        return redirect('adminstore:company')

apps/adminstore/views/ManageDiscount.py
from django.contrib import messages
from django.contrib.auth.mixins import UserPassesTestMixin
from django.core.paginator import Paginator, EmptyPage
from django.db.models import Q
from django.shortcuts import redirect, render
from django.views import View

from apps.shop.models import Discount




class ManageDiscount(UserPassesTestMixin, View):
    """
    Gestiona los descuentos disponibles en la tienda virtual.
    """
    http_method_names = ['get', 'post', 'put', 'delete']


    def test_func(self):
        """
        Solamente están autorizados a acceder a esta página los
        usuarios con el atributo is_staff=True.
        """
        return self.request.user.is_staff


    def handle_no_permission(self):
        """
        Si un usuario tiene acceso denegado, se redirecciona al inicio.
        """
        messages.warning(self.request, '¡Acceso denegado!')
        return redirect('shop:home')


    def dispatch(self, *args, **kwargs):
        """
        Maneja las solicitudes PUT y DELETE a través de un campo
        <input type="hidden" name="_method" value="put|delete">
        debido a que los formulario HTML solo permiten GET o POST.
        """
        method = self.request.POST.get('_method', '').lower()
        if method == 'put':
            return self.put(*args, **kwargs)
        if method == 'delete':
            return self.delete(*args, **kwargs)
        return super(ManageDiscount, self).dispatch(*args, **kwargs)


    def get(self, request):
        """
        Muestra la tabla con los descuentos existentes en la base de datos.
        """
        # Obtenemos todas los descuentos.
        discounts = Discount.objects.filter(is_active=True).order_by('pk')

        # Obtenemos el valor del cuadro de búsqueda.
        query = request.GET.get('q')

        # Si se ingresó algo en el cuadro de búsqueda, se filtran los descuentos.
        if query:
            discounts = discounts.filter(
                Q(name__icontains=query) |
                Q(percentage__icontains=query)
            )

        # Creamos el objeto paginador.
        obj_per_page = 25
        paginator = Paginator(discounts, obj_per_page)
        num_page = request.GET.get('page')

        try:
            page = paginator.get_page(num_page)
        except EmptyPage:
            # Si la URL no tiene ?page= devuelve la primera página.
            page = paginator.get_page(1)

        context = {
            'discounts': discounts,
            'page': page,
        }

        return render(request, 'adminstore/discount/show.html', context)


    def post(self, request):
        """
        Agrega un nuevo descuento a la base de datos.
        """
        # Obtenemos los datos del formulario.
        name = request.POST.get('name')
        percentage = request.POST.get('percentage')
        created_at = request.POST.get('created_at')
        finish_at = request.POST.get('finish_at')

        # Creamos el registro en la base de datos.
        Discount.objects.create(
            name=name,
            percentage=percentage,
            created_at=created_at,
            finish_at=finish_at
        )

        # Redirigimos a la misma página de gestión de descuentos.
        messages.success(request, '¡Haz agregado un nuevo descuento!')
        return redirect('adminstore:discounts')


    def put(self, request):
        """
        Actualiza un descuento en la base de datos.
        """
        # Obtenemos los datos del formulario.
        discount_id = request.POST['id']
        name = request.POST['name']
        percentage = request.POST['percentage']
        created_at = request.POST['created_at']
        finish_at = request.POST['finish_at']

        # Obtenemos el descuento de la base de datos.
        discount = Discount.objects.get(pk=discount_id)

        # Actualizamos el registro.
        discount.name = name
        discount.percentage = percentage
        discount.created_at = created_at
        discount.finish_at = finish_at
        discount.save()

        # Redirigimos a la misma página de gestión de descuentos.
        messages.success(request, '¡Haz modificado un descuento!')
        return redirect('adminstore:discounts')


    def delete(self, request):
        """
        Elimina un descuento de la base de datos.
        """
        # Obtenemos los datos del formulario.
        discount_id = request.POST['id']

        # Obtenemos el descuento de la base de datos.
        discount = Discount.objects.get(pk=discount_id)

        # Actualizamos el registro.
        discount.is_active = False
        discount.save()

        # Redirigimos a la misma página de gestión de descuentos.
        messages.warning(request, '¡Haz eliminado un descuento!')
        return redirect('adminstore:discounts')

templates/adminstore/user/show.html
{% extends "../../base.html" %}


{% load static %}
{% load humanize %}


{% block title %}Gestionar permisos de usuarios {{ block.super }} {% endblock %}


{% block content %}
    {% include '../includes/admin_navbar.html' %}

    <div class="container">
        <div class="row my-5">
            <div class="admin-title mb-5">
                <h1 class="fw-bold">Gestionar permisos</h1>
                <small>Asigna o remueve administradores del sitio web.</small>
            </div>
            <div class="col-md-11 col-lg-10 mx-auto">
                <div class="d-flex flex-row-reverse justify-content-between mb-4">
                    <form class="d-flex" action="{% url 'adminstore:users' %}" method="GET">
                        <input class="form-control me-2" type="search" name="q" placeholder="Buscar" aria-label="Buscar" style="flex: 0 1 300px;">
                        <button class="btn btn-outline-primary" type="submit">Buscar</button>
                    </form>
                </div>
                <div class="table-responsive">
                    <table class="table table-hover align-middle">
                        <thead>
                            <tr>
                                <th class="sortable text-center"></th>
                                <th class="sortable text-center">Nombre de usuario</th>
                                <th class="sortable text-center">Nombre completo</th>
                                <th class="sortable text-center">Correo electrónico</th>
                                <th class="sortable text-center">Fecha de creación</th>
                                <th class="sortable text-center">¿Es administrador?</th>
                                <th class="sortable text-center"></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for user in page.object_list %}
                                <tr>
                                    <td class="text-center">
                                        {% if user.photo %}
                                            <img class="img-fluid rounded-circle" src="../../../media/{{ user.photo }}" width="75" alt="profile photo">
                                        {% else %}
                                            <img class="img-fluid rounded-circle" src="{% static 'img/default.jpg' %}" width="75" alt="profile photo">
                                        {% endif %}
                                    </td>
                                    <td class="text-center">{{ user.username }}</td>
                                    <td class="text-center">{% if user.get_full_name %} {{ user.get_full_name }} {% else %} <span class="text-muted">???</span> {% endif %}</td>
                                    <td class="text-center">{% if user.email %} {{ user.email }} {% else %} <span class="text-muted">???</span> {% endif %}</td>
                                    <td class="text-center">{{ user.date_joined|date:'d/m/Y' }}</td>
                                    <td class="text-center">
                                        {% if user.is_staff %}
                                            <i class="fas fa-check text-success"></i>
                                        {% else %}
                                            <i class="fas fa-times text-danger"></i>
                                        {% endif %}
                                    </td>
                                    <td class=" text-center">
                                        <a href="#" data-bs-toggle="modal" data-bs-target="#update_{{ user.pk }}" title="Modificar permisos">
                                            <i class="fas fa-marker"></i>
                                        </a>
                                        {% include './update.html' %}
                                    </td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td class="text-center text-muted py-5" colspan="9">No hay resultados</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="text-end mt-4">
                    {% if request.GET.q %}
                        <a href="{% url 'adminstore:users' %}" class="btn btn-outline-secondary">
                            <small>Ver todo</small>
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="row mb-5">
            <div class="col-md-11 col-lg-10 mx-auto">
                {% if page.has_other_pages %}
                    <nav aria-label="Page navigation mt-5">
                        <ul class="pagination justify-content-center">
                            {% if page.has_previous %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ page.previous_page_number }}">Anterior</a>
                                </li>
                            {% endif %}

                            {% for num in page.paginator.page_range %}
                                {% if num == page.number %}
                                    <li class="page-item active" aria-current="page">
                                        <a class="page-link" href="#">{{ num }}</a>
                                    </li>
                                {% else %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                                    </li>
                                {% endif %}
                            {% endfor %}

                            {% if page.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ page.next_page_number }}">Siguiente</a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}


{% block js %}
    <script>
        // Ordena una tabla al dar clic sobre el encabezado de una columna.
        // El encabezado debe tener la clase .sortable.
        //------ No ordena datos paginados.
        $(document).ready(function() {
            $('.sortable').click(function() {
            let table = $(this).closest('table');
            let rows = table.find('tbody > tr').get();
            let index = $(this).index();
            let sortOrder = $(this).hasClass('asc') ? -1 : 1;

            rows.sort(function(a, b) {
                let aValue = $(a).find('td').eq(index).text();
                let bValue = $(b).find('td').eq(index).text();

                if ($.isNumeric(aValue) && $.isNumeric(bValue)) {
                    return sortOrder * (parseFloat(aValue) - parseFloat(bValue));
                } else {
                    return sortOrder * aValue.localeCompare(bValue, undefined, { numeric: true });
                }
            });

            table.children('tbody').empty().append(rows);
            $(this).toggleClass('asc');
            });
        });


        // Habilita el uso de tooltips.
        $(document).ready(function(){
            $('[data-bs-toggle="tooltip"]').tooltip();
        });
    </script>
{% endblock %}

templates/adminstore/user/update.html
<div class="modal fade" id="update_{{ user.pk }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title fw-bold" id="exampleModalLabel"><i class="fas fa-pen"></i> &nbsp; Modificar permisos a {{ user.get_full_name }}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{% url 'adminstore:users' %}" method="POST" class="text-start">
                {% csrf_token %}
                <div class="modal-body">
                    <div class="container">
                        <div class="row">
                            <input type="hidden" name="_method" value="put">
                            <input type="hidden" name="id" value="{{ user.pk }}">
                            <div class="my-2">
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="is_staff" id="is_staff_1" value="1" {% if user.is_staff %} checked {% endif %}>
                                    <label class="form-check-label" for="is_staff_1">
                                        Asignar permisos de administrador.
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="is_staff" id="is_staff_2" value="0" {% if not user.is_staff %} checked {% endif %}>
                                    <label class="form-check-label" for="is_staff_2">
                                        Remover permisos de administrador.
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-warning">Modificar</button>
                </div>
            </form>
        </div>
    </div>
</div>