apps/accounts/urls.py
from django.urls import path

from apps.accounts import views




app_name = 'accounts'


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('signin/', views.SignIn.as_view(), name='signin'),
    path('signout/', views.SignOut.as_view(), name='signout'),

    path('profile/', views.Profile.as_view(), name='profile'),
    path('profile/update', views.UpdateProfile.as_view(), name='update-profile'),
    path('profile/change-photo', views.ChangeProfilePhoto.as_view(), name='change-photo'),
    path('profile/delete-photo', views.DeleteProfilePhoto.as_view(), name='delete-photo'),
    path('profile/delete-address', views.DeleteProfileAddress.as_view(), name='delete-address'),
    path('profile/add-address', views.AddProfileAddress.as_view(), name='add-address'),
    path('profile/delete', views.DeleteAccount.as_view(), name='delete-account'),

    path('change-password/', views.ChangePassword.as_view(), name='change-password'),
    path('reset-password/', views.AskResetPassword.as_view(), name='ask-reset-password'),
    path('reset/<str:token>/', views.ResetPassword.as_view(), name='reset-password'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path




urlpatterns = [
    path('', include('apps.accounts.urls')),
    path('', include('apps.shop.urls')),
    path('', include('apps.utils.urls')),
    path('admin-store/', include('apps.adminstore.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/models/City.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.accounts.models import Region




class City(models.Model):
    """
    Ciudades de Colombia.
    """
    name = models.CharField(max_length=75, verbose_name=_('nombre'))
    region = models.ForeignKey('accounts.Region', on_delete=models.CASCADE, verbose_name=_('departamento'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('fecha de creación'))
    updated_at = models.DateTimeField(auto_now=True, verbose_name=_('fecha de actualización'))
    is_active = models.BooleanField(default=True, verbose_name=_('activo'))


    def __str__(self):
        return f'{self.name}'


    class Meta:
        verbose_name = _('ciudad')
        verbose_name_plural = _('ciudades')

apps/accounts/models/Contact.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.accounts.models import City, Region, User




class Contact(models.Model):
    """
    Información de contacto de los usuarios de la aplicación.
    """
    user = models.ForeignKey('accounts.User', on_delete=models.CASCADE, verbose_name=_('usuario'))
    region = models.ForeignKey('accounts.Region', on_delete=models.DO_NOTHING, verbose_name=_('departamento'))
    city = models.ForeignKey('accounts.City', on_delete=models.DO_NOTHING, verbose_name=_('ciudad'))
    address = models.CharField(max_length=75, verbose_name=_('dirección'))
    phone = models.CharField(max_length=10, verbose_name=_('teléfono'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('fecha de creación'))
    updated_at = models.DateTimeField(auto_now=True, verbose_name=_('fecha de actualización'))
    is_active = models.BooleanField(default=True, verbose_name=_('activo'))


    def __str__(self):
        return f'{self.user.username}\'s contact'


    class Meta:
        verbose_name = _('información de contacto')
        verbose_name_plural = _('informacion de contacto')

apps/accounts/views/ChangePassword.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import redirect, render
from django.views import View
from apps.shop.models import ShoppingCart, ShoppingCartProduct




class ChangePassword(LoginRequiredMixin, View):
    """
    Cambia la contraseña del usuario autenticado.
    """
    login_url = reverse_lazy('accounts:signin')

    def get(self, request):
        """
        Muestra el formulario para cambiar la contraseña.
        """

        user = request.user

        if user.is_authenticated:
            # Obtener el carrito del usuario
            try:
                shopping_cart = ShoppingCart.objects.get(user=user, is_active=True)
            except ShoppingCart.DoesNotExist:
                shopping_cart = None
            
            # Obtener la cantidad de productos en el carrito
            if shopping_cart:
                product_count = ShoppingCartProduct.objects.filter(cart=shopping_cart).count()
            else:
                product_count = 0
        else:
            product_count = None

        context = {
            'user': user,
            'products_cart_count': product_count
        }
        return render(request, 'accounts/profile/change_password.html', context)


    def post(self, request):
        """
        Cambia la contraseña del usuario.
        """
        # Obtenemos los datos del formulario.
        password = request.POST['password1']

        # Obtenemos el usuario autenticado.
        user = request.user

        # Validamos que el usuario no cambie la contraseña por la misma.
        if user.check_password(password):
            messages.error(request, 'La contraseña no puede ser la misma!')
            return redirect('accounts:change-password')

        # Actualizamos la contraseña del usuario en la base de datos.
        user.set_password(password)
        user.save()

        # Mostramos un mensaje indicando que el proceso ha sido exitoso.
        messages.success(
            request, 'Tu contraseña ha cambiado. Por favor inicia sesión de nuevo')

        # Redirigimos al usuario a la vista de login para que inicie sesión.
        return redirect('accounts:signin')

apps/accounts/views/Profile.py
from io import BytesIO
import os

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.urls import reverse_lazy
from django.shortcuts import redirect, render
from django.views import View
from apps.shop.models import ShoppingCart, ShoppingCartProduct

from PIL import Image

from apps.accounts.models import City, Contact, Region




class Profile(LoginRequiredMixin, View):
    """
    Muestra la página con la información de perfil del usuario autenticado.
    """
    login_url = reverse_lazy('accounts:signin')

    def get(self, request):
        """
        Muestra la información de perfil del usuario autenticado.
        """
        user = request.user
        contacts = Contact.objects.filter(user=user.id, is_active=True)

        if user.is_authenticated:
            # Obtener el carrito del usuario
            try:
                shopping_cart = ShoppingCart.objects.get(user=user, is_active=True)
            except ShoppingCart.DoesNotExist:
                shopping_cart = None
            
            # Obtener la cantidad de productos en el carrito
            if shopping_cart:
                product_count = ShoppingCartProduct.objects.filter(cart=shopping_cart).count()
            else:
                product_count = 0
        else:
            product_count = None

        context = {
            'user': user,
            'contacts': contacts,
            'products_cart_count': product_count
        }

        return render(request, 'accounts/profile/profile.html', context)




class ChangeProfilePhoto(LoginRequiredMixin, View):
    """
    Cambia la foto de perfil del usuario autenticado.
    """
    login_url = reverse_lazy('accounts:signin')

    def post(self, request):
        """
        Valida que el archivo enviado sea una imagen y actualiza
        la foto de perfil del usuario autenticado en la base de datos.
        """
        # Obtenemos el archivo subido.
        uploaded_file = request.FILES.get('photo')

        # Verificamos que el archivo sea una imagen.
        try:
            img = Image.open(uploaded_file)
        except Exception:
            messages.error(request, '¡El archivo no es una imagen!')
            return redirect('accounts:profile')

        # Obtenemos el usuario autenticado.
        user = request.user

        # Redimensionamos la imagen.
        width, height = img.size
        shortest_side = min(width, height)
        new_img = Image.new('RGB', (shortest_side, shortest_side), (255, 255, 255))
        new_img.paste(img, ((shortest_side - width) // 2, (shortest_side - height) // 2))
        new_img = new_img.resize((200, 200))
        buf = BytesIO()
        new_img.save(buf, format='JPEG')
        new_file = InMemoryUploadedFile(buf, None, 'filename.jpg', 'image/jpeg', buf.tell(), None)

        # Eliminamos la foto de perfil si ya existe una anterior.
        if user.photo:
            storage = user.photo.storage
            storage.delete(user.photo.path)

        # Actualizamos la foto del usuario.
        user.photo.save(f'photo_{user.pk}.jpg', new_file, save=False)
        user.save()

        # Redirigimos a la página del perfil de usuario.
        messages.success(request, '¡La foto de perfil ha sido actualizada!')
        return redirect('accounts:profile')




class DeleteProfilePhoto(LoginRequiredMixin, View):
    """
    Elimina la foto de perfil del usuario autenticado.
    """
    login_url = reverse_lazy('accounts:signin')

    def post(self, request):
        """
        Reemplaza la foto de perfil por una imagen genérica.
        """
        # Obtenemos el usuario autenticado.
        user = request.user

        # Eliminamos la foto de perfil si ya existe una anterior.
        if user.photo:
            storage = user.photo.storage
            storage.delete(user.photo.path)

            user.photo = ''
            user.save()

        # Redirigimos a la página del perfil de usuario.
        messages.success(request, '¡La foto de perfil ha sido eliminada!')
        return redirect('accounts:profile')




class DeleteProfileAddress(LoginRequiredMixin, View):
    """
    Elimina una dirección asociada con el perfil del usuario autenticado.
    """
    login_url = reverse_lazy('accounts:signin')

    def post(self, request):
        """
        Elimina la dirección asociada.
        """
        # Obtenemos los datos del formulario.
        contact_id = request.POST['contact_id']

        # Obtenemos la información de contacto.
        contact = Contact.objects.get(pk=contact_id)

        # Eliminamos (ocultamos) la información de contacto.
        contact.is_active = False
        contact.save()

        # Redirigimos a la página del perfil de usuario.
        messages.success(request, '¡La información de contacto ha sido actualizada!')
        return redirect('accounts:profile')




class AddProfileAddress(LoginRequiredMixin, View):
    """
    Agrega una dirección de contacto al perfil del usuario autenticado.
    """
    login_url = reverse_lazy('accounts:signin')

    def get(self, request):
        """
        Muestra el formulario para agregar una nueva dirección de contacto.
        """
        user = request.user

        if user.is_authenticated:
            # Obtener el carrito del usuario
            try:
                shopping_cart = ShoppingCart.objects.get(user=user, is_active=True)
            except ShoppingCart.DoesNotExist:
                shopping_cart = None
            
            # Obtener la cantidad de productos en el carrito
            if shopping_cart:
                product_count = ShoppingCartProduct.objects.filter(cart=shopping_cart).count()
            else:
                product_count = 0
        else:
            product_count = None

        context = {
            'cities': City.objects.filter(is_active=True),
            'regions': Region.objects.filter(is_active=True),
            'products_cart_count': product_count
        }
        return render(request, 'accounts/profile/add_address.html', context)


    def post(self, request):
        """
        Guarda la nueva dirección de contacto en la base de datos.
        """
        # Obtenemos los datos del formulario.
        address = request.POST['address']
        city_id = request.POST['city']
        region_id = request.POST['region']
        phone = request.POST['phone']

        # Obtenemos el usuario autenticado.
        user = request.user

        # Creamos el registro correspondiente en la tabla de Contacto.
        city = City.objects.get(pk=city_id)
        region = Region.objects.get(pk=region_id)

        contact = Contact(
            user=user,
            region=region,
            city=city,
            address=address,
            phone=phone
        )
        contact.save()

        # Redirigimos a la página del perfil de usuario.
        messages.success(request, '¡La información de contacto ha sido actualizada!')
        return redirect('accounts:profile')




class UpdateProfile(LoginRequiredMixin, View):
    """
    Actualiza la información del usuario autenticado.
    """
    login_url = reverse_lazy('accounts:signin')

    def get(self, request):
        """
        Muestra el formulario para actualizar la información personal del usuario.
        """
        user = request.user

        if user.is_authenticated:
            # Obtener el carrito del usuario
            try:
                shopping_cart = ShoppingCart.objects.get(user=user, is_active=True)
            except ShoppingCart.DoesNotExist:
                shopping_cart = None
            
            # Obtener la cantidad de productos en el carrito
            if shopping_cart:
                product_count = ShoppingCartProduct.objects.filter(cart=shopping_cart).count()
            else:
                product_count = 0
        else:
            product_count = None

        context = {
            'user': user,
            'products_cart_count': product_count
        }
        return render(request, 'accounts/profile/update_user.html', context)


    def post(self, request):
        """
        Guarda la información del usuario en la base de datos.
        """
        # Obtenemos los datos del formulario.
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        birthdate = request.POST['birthdate']

        # Obtenemos el usuario autenticado.
        user = request.user

        # Actualizamos la información del usuario.
        user.first_name = first_name
        user.last_name = last_name
        user.username = username
        user.email = email
        user.birthdate = birthdate
        user.save()

        # Redirigimos a la página del perfil de usuario.
        messages.success(request, '¡La información personal ha sido actualizada!')
        return redirect('accounts:profile')




class DeleteAccount(LoginRequiredMixin, View):
    """
    Elimina la cuenta de usuario.
    """
    login_url = reverse_lazy('accounts:signin')

    def get(self, request):
        """
        Muestra el formulario para eliminar la cuenta de usuario.
        """
        user = request.user

        if user.is_authenticated:
            # Obtener el carrito del usuario
            try:
                shopping_cart = ShoppingCart.objects.get(user=user, is_active=True)
            except ShoppingCart.DoesNotExist:
                shopping_cart = None
            
            # Obtener la cantidad de productos en el carrito
            if shopping_cart:
                product_count = ShoppingCartProduct.objects.filter(cart=shopping_cart).count()
            else:
                product_count = 0
        else:
            product_count = None

        context = {
            'user': user,

apps/accounts/views/SignIn.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, render
from django.views import View




class SignIn(View):
    """
    Inicio de sesión.
    """

    def get(self, request):
        """
        Muestra el formulario para iniciar sesión.
        """
        return render(request, 'accounts/signin.html')


    def post(self, request):
        """
        Valida las credenciales para el inicio de sesión.
        """
        # Obtenemos los datos del formulario.
        username = request.POST['username']
        password = request.POST['password']
        remember_me = request.POST.get('remember-me', False)

        # Buscamos un usuario con esas credenciales.
        user = authenticate(username=username, password=password)

        # Si el usuario existe, lo redirigimos al home.
        if user:
            login(request, user)

            # Si se ha marcado la casilla Recuérdame, guarda la sesión por 30 días.
            if remember_me:
                request.session.set_expiry(30)
                response = redirect('shop:home')
                response.set_cookie('remember_me', user.pk, max_age=30)
                return response

            return redirect('shop:home')

        # Si el usuario no existe, mostramos el formulario con un mensaje de error.
        else:
            messages.error(request, 'El usuario y/o contraseña son incorrectos.')
            return redirect('accounts:signin')

apps/accounts/views/SignOut.py
from django.contrib import messages
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.views import View




class SignOut(View):
    """
    Cierre de sesión de usuario actual.
    """

    def get(self, request):
        logout(request)
        messages.success(request, '¡Cierre de sesión exitoso!')
        return redirect('shop:home')

templates/accounts/profile/add_address.html
{% extends "../../base.html" %}


{% load static %}


{% block title %} Agregar dirección de contacto {{ block.super }} {% endblock %}


{% block content %}
    <div class="container">
        <div class="row d-flex justify-content-around align-items-center">
            <div class="col-xl-4 col-lg-5 col-md-6">

                <h2 class="mt-2 fw-bold">Nueva dirección de contacto</h2>
                <hr>

                <form id="address_form" class="mt-5" action="{% url 'accounts:add-address' %}" method="POST">
                    {% csrf_token %}
                    <div class="mb-4">
                        <label for="address" class="form-label fw-bold">Dirección del domicilio <span class="text-danger">*</span></label>
                        <input type="text" class="form-control mb-2" id="address" name="address" required>
                    </div>

                    <div class="mb-4">
                        <label for="region" class="form-label fw-bold">Departamento <span class="text-danger">*</span></label>
                        <select class="form-select" id="region" name="region" required>
                            <option selected></option>
                            {% for region in regions %}
                                <option value="{{ region.id }}">{{ region.name }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="mb-4">
                        <label for="city" class="form-label fw-bold">Ciudad <span class="text-danger">*</span></label>
                        <select class="form-select" id="city" name="city" required>
                            <option selected></option>
                        </select>
                    </div>

                    <div class="mb-4">
                        <label for="phone" class="form-label fw-bold">Número de teléfono <span class="text-danger">*</span></label>
                        <input type="number" class="form-control" id="phone" name="phone" onkeyup="validate_phone()" required>
                        <small class="text-danger" id="phone-help"></small>
                    </div>

                    <div class="d-grid gap-2 d-md-flex justify-content-md-start mt-5">
                        <button type="submit" class="btn btn-primary" id="submit-btn">
                            Añadir
                        </button>
                    </div>
                </form>
            </div>
            <div class="col-xl-4 col-lg-5 col-md-6 d-none d-md-block my-5">
                <div class="img-container">
                    <img class="img-fluid rounded float-end shadow" src="{% static 'img/map.jpg' %}" alt="login image">
                </div>
            </div>
        </div>
    </div>
{% endblock content %}


{% block js %}
    <script src="{% static 'js/accounts/validators.js' %}"></script>
    <script src="{% static 'js/accounts/dynamic_cities.js' %}"></script>
{% endblock %}

templates/accounts/profile/delete_account.html
{% extends "../../base.html" %}


{% load static %}


{% block title %} Eliminar cuenta de usuario {{ block.super }} {% endblock %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xxl-5 col-xl-6 col-lg-7 col-md-8 col-sm-10">

                <h2 class="mt-2 fw-bold">Eliminar cuenta de usuario</h2>
                <hr>

                <form id="delete_account_form" class="mt-5" action="{% url 'accounts:delete-account' %}" method="POST">
                    {% csrf_token %}

                    <p>Presiona el botón <strong>Eliminar cuenta</strong> para desactivar tu cuenta de usuario de TecnoBox.</p>

                    <div class="d-grid gap-2 d-md-flex justify-content-md-start mt-5">
                        <button type="submit" class="btn btn-danger">
                            Eliminar cuenta
                        </button>
                    </div>

                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/accounts/profile/modal.html
<div id="modal" class="modal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Advertencia</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>¿Estás seguro de querer eliminar esta dirección de contacto?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
          <button id="accept-modal-btn" type="button" class="btn btn-danger">Aceptar</button>
        </div>
      </div>
    </div>
</div>

templates/accounts/profile/profile.html
{% extends "../../base.html" %}


{% load static %}


{% block title %} Mi perfil {{ block.super }} {% endblock %}


{% block content %}
    <div class="container">

        <div class="row">
            <div class="col-md-3 mt-4 mb-4 text-center">
                <h1 class="mb-4"><strong>Mi perfil</strong></h1>
                <div id="profile-photo-container">
                    {% if user.photo %}
                        <img class="img-fluid rounded-circle border border-dark border-4" src="../../media/{{ user.photo }}" alt="profile photo" width="200" height="200">
                    {% else %}
                        <img class="img-fluid rounded-circle border border-dark border-4" src="../../static/img/default.jpg" alt="profile photo" width="200" height="200">
                    {% endif %}
                    <br>
                    <button id="profile-photo-edit-btn"><i class="fas fa-edit"></i></button>
                    <div id="profile-photo-edit-menu">
                        <a id="delete-photo-link" href="#">Eliminar foto</a>
                        <form class="d-none" id="delete-photo-form" method="POST" action="{% url 'accounts:delete-photo' %}">
                            {% csrf_token %}
                            <input type="hidden" name="delete_photo" value="true">
                            <button type="submit">Eliminar foto</button>
                        </form>
                        <a id="change-photo-link" href="#">Cambiar foto</a>
                        <form class="d-none" id="change-photo-form" method="POST" action="{% url 'accounts:change-photo' %}" enctype="multipart/form-data">
                            {% csrf_token %}
                            <input type="file" name="photo">
                            <button type="submit">Guardar foto</button>
                        </form>
                    </div>
                </div>
            </div>

            <div class="col-md-9 mt-md-5">
                <div class="row mb-5 mt-md-5 mt-4">
                    <h2 class="fs-5"><strong>Información Personal</strong></h2>
                    <hr>
                    <div class="row">
                        <div class="col-md-6">
                            <div><strong>Nombre completo:</strong> {{ user.get_full_name }}</div>
                            <div><strong>Cumpleaños:</strong> {{ user.birthdate }}</div>
                        </div>
                        <div class="col-md-6">
                            <div><strong>Nombre de usuario:</strong> {{ user.username }}</div>
                            <div><strong>Correo electrónico:</strong> {{ user.email }}</div>
                        </div>
                    </div>
                    <a class="mt-3" href="{% url 'accounts:update-profile' %}"><small>Modificar información personal.</small></a>
                    <a href="{% url 'accounts:change-password' %}"><small>Cambiar contraseña.</small></a>
                    <a href="{% url 'accounts:delete-account' %}" class="mt-3 text-danger"><small>Eliminar cuenta.</small></a>
                </div>

                <div class="row mb-5">
                    <h2 class="fs-5"><strong>Direcciones de entrega</strong></h2>
                    <hr>
                    {% for contact in contacts %}
                        <div>
                            <a id="delete-address" href="#" title="Eliminar dirección" data-bs-toggle="modal" data-bs-target="#modal">
                                <i class="fas fa-times" style="color: #e53434;"></i>
                            </a>
                            <form class="d-none" id="delete-address-form" method="POST" action="{% url 'accounts:delete-address' %}">
                                {% csrf_token %}
                                <input type="hidden" name="contact_id" value="{{ contact.pk }}">
                                <button type="submit">Eliminar dirección</button>
                            </form>
                            &nbsp;&nbsp;
                            {{ contact.address }}, {{ contact.city }}, {{ contact.region }}. <i>Tel.:</i> {{ contact.phone }}
                            {% include './modal.html' %}
                        </div>
                    {% empty %}
                        <p class="text-muted">Aún no hay direcciones asociadas con tu cuenta.</p>
                    {% endfor %}
                    <a class="mt-3" href="{% url 'accounts:add-address' %}"><small>Añadir otra dirección de contacto.</small></a>
                </div>

                <div class="row mb-5">
                    <h2 class="fs-5"><strong>Mis órdenes</strong></h2>
                    <hr>
                    <p class="text-muted">Aún no has realizado ninguna órden de compra.</p>
                </div>

                <div class="row mb-5">
                    <h2 class="fs-5"><strong>Mis reseñas</strong></h2>
                    <hr>
                    <p class="text-muted">Aún no has realizado ninguna reseña.</p>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}


{% block js %}
    <script>
        // Seleccionamos el botón y el menú emergente.
        const editButton = document.querySelector('#profile-photo-edit-btn');
        const editMenu = document.querySelector('#profile-photo-edit-menu');

        // Cuando se hace clic en el botón, mostramos el menú emergente.
        editButton.addEventListener('click', function() {
            editMenu.style.display = 'block';
        });

        // Cuando se hace clic en cualquier lugar fuera del menú emergente, lo ocultamos.
        document.addEventListener('click', function(event) {
            if (!editMenu.contains(event.target) && !editButton.contains(event.target)) {
                editMenu.style.display = 'none';
            }
        });


        // Manejo de los formularios para:
        // eliminar foto de perfil, cambiar foto de perfil y eliminar dirección.
        document.addEventListener('DOMContentLoaded', function() {
            const changePhotoLink = document.querySelector('#change-photo-link');
            const changePhotoForm = document.querySelector('#change-photo-form');
            const fileInput = document.querySelector('#change-photo-form input[type="file"]');
            const deletePhotoLink = document.querySelector('#delete-photo-link');
            const deletePhotoForm = document.querySelector('#delete-photo-form');
            const deleteAddress = document.querySelector('#accept-modal-btn');
            const deleteAddressForm = document.querySelector('#delete-address-form');

            // Cuando se hace clic en el enlace para cambiar foto, se activa el input de fichero.
            changePhotoLink.addEventListener('click', function(event) {
                event.preventDefault();
                fileInput.click();
            });

            // Cuando se selecciona una foto, el formulario de cambio de foto se envía automáticamente.
            fileInput.addEventListener('change', function(event) {
                changePhotoForm.submit();
            });

            // Cuando se hace clic en eliminar foto, se envía el formulario correspondiente.
            deletePhotoLink.addEventListener('click', function(event) {
                event.preventDefault();
                deletePhotoForm.submit();
            });

            // Cuando se hace clic en eliminar dirección, se envía el formulario correspondiente.
            deleteAddress.addEventListener('click', function(event) {
                event.preventDefault();
                deleteAddressForm.submit();
            });
        });
    </script>
{% endblock %}