apps/shop/urls.py
from django.urls import path

from apps.shop import views




app_name = 'shop'


urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about-us/', views.AboutUs.as_view(), name='about-us'),
    path('contact-us/', views.ContactUs.as_view(), name='contact-us'),
    path('products/', views.Products.as_view(), name='products'),
    path('products/<int:product_id>/', views.Detail.as_view(), name='detail'),
    path('products/<int:product_id>/make-review/', views.MakeReview.as_view(), name='make-review'),
    path('discounts/',views.Discounts.as_view(), name='discounts' ),
    path('cart/', views.Cart.as_view(), name='cart'),
    path('bill/', views.FacturaPDF.as_view(), name='bill'),
    path('increase-quantity/<int:product_id>/', views.Cart.increase_quantity, name='increase-quantity'),
    path('decrease-quantity/<int:product_id>/', views.Cart.decrease_quantity, name='decrease-quantity'),
    path('remove-from-cart/<int:product_id>/', views.Cart.remove_from_cart, name='remove-from-cart'),
    path('empty-car/', views.Cart.empty_cart, name='empty-cart'),
    path('purchase', views.Cart.purchase, name='purchase'),
    path('terms-and-conditions/', views.TermsAndConditions.as_view(), name='terms-and-conditions'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path




urlpatterns = [
    path('', include('apps.accounts.urls')),
    path('', include('apps.shop.urls')),
    path('', include('apps.utils.urls')),
    path('admin-store/', include('apps.adminstore.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/shop/views/AboutUs.py
from django.shortcuts import render
from django.views import View
from django.db.models import Sum, Max
from apps.shop.models import ShoppingCartProduct, ShoppingCart




class AboutUs(View):
    """
    Página "Sobre Nosotros".
    """

    def get(self, request):
        """
        Muestra la página con información sobre la empresa.
        """

        # User
        user = request.user

        if user.is_authenticated:
            # Obtener el carrito del usuario
            try:
                shopping_cart = ShoppingCart.objects.get(user=user, is_active=True)
            except ShoppingCart.DoesNotExist:
                shopping_cart = None
            
            # Obtener la cantidad de productos en el carrito
            if shopping_cart:
                product_count = ShoppingCartProduct.objects.filter(cart=shopping_cart).count()
            else:
                product_count = 0
        else:
            product_count = None

        context = {
            'user' : user,
            'products_cart_count': product_count,
            'path' : request.path
        }
        return render(request, 'shop/about_us.html', context)

apps/shop/views/Cart.py
from io import BytesIO
from decimal import Decimal

from django.http import HttpResponse
from django.template.loader import get_template
from django.views import View
from django.shortcuts import get_object_or_404,render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.db import transaction

from apps.shop.models import ShoppingCart, ShoppingCartProduct, Product, PurchaseOrder, OrderProduct, PaymentMethod
from apps.accounts.models import Contact

from xhtml2pdf import pisa



def render_to_pdf(template_src, context_dict={}):
    template = get_template(template_src)
    html  = template.render(context_dict)
    result = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode("UTF-8")), result)
    if not pdf.err:
        return HttpResponse(result.getvalue(), content_type='application/pdf')
    return None



class Cart(LoginRequiredMixin,View):

    login_url = reverse_lazy('accounts:signin')

    def get(self, request):

        # Obtener el usuario autenticado
        user = request.user

        # Obtener el carrito del usuario
        try:
            shopping_cart = ShoppingCart.objects.get(user=user, is_active=True)
        except ShoppingCart.DoesNotExist:
            shopping_cart = None

        # Obtener los productos en el carrito y calcular el total del valor de la compra
        products = []
        total_price = 0
        total_discount = 0
        if shopping_cart:
            cart_products = ShoppingCartProduct.objects.filter(cart=shopping_cart)
            product_instances = {}
            for cart_product in cart_products:
                product = cart_product.product
                if product in product_instances:
                    product_instances[product] += cart_product.amount
                else:
                    product_instances[product] = cart_product.amount
                total_price += product.price * cart_product.amount

            # Crear una lista de productos únicos con la cantidad de unidades, precio con descuento y subtotal
            for product, amount in product_instances.items():
                discount_price = product.price
                if product.discounts.exists():
                    discount = product.discounts.first()
                    discount_price -= discount.discount_value
                    total_discount += discount.discount_value*amount
                subtotal = discount_price * amount
                products.append({
                    'product': product,
                    'amount': amount,
                    'subtotal': subtotal,
                    'price_with_discount': discount_price
                })

        context = {
            'products': products,
            'total_price': total_price,
            'total_discount': total_discount,
            'products_cart_count': len(products)
        }
        return render(request, 'shop/cart.html', context)

    def increase_quantity(request, product_id):
        # Obtener el producto seleccionado
        product = Product.objects.get(pk=product_id)

        # Verificar si el carrito de compras ya existe para el usuario actual
        cart, created = ShoppingCart.objects.get_or_create(user=request.user)

        # Verificar si el producto ya está en el carrito de compras
        cart_product, created = ShoppingCartProduct.objects.get_or_create(cart=cart, product=product)

        # Incrementar la cantidad del producto en el carrito
        cart_product.amount += 1
        cart_product.save()

        return redirect('shop:cart')  # Redirigir a la página del carrito de compras


    def decrease_quantity(request, product_id):
        # Obtener el producto seleccionado
        product = Product.objects.get(pk=product_id)

        # Obtener el carrito de compras del usuario actual
        cart = ShoppingCart.objects.get(user=request.user)

        # Obtener el producto en el carrito de compras
        cart_product = ShoppingCartProduct.objects.get(cart=cart, product=product)

        # Disminuir la cantidad del producto en el carrito
        if cart_product.amount > 1:
            cart_product.amount -= 1
            cart_product.save()

        return redirect('shop:cart')  # Redirigir a la página del carrito de compras


    def remove_from_cart(request, product_id):
        # Obtener el producto seleccionado
        product = Product.objects.get(pk=product_id)

        # Obtener el carrito de compras del usuario actual
        cart = ShoppingCart.objects.get(user=request.user)

        # Obtener el producto en el carrito de compras
        cart_product = ShoppingCartProduct.objects.get(cart=cart, product=product)

        # Eliminar el producto del carrito
        cart_product.delete()

        return redirect('shop:cart')  # Redirigir a la página del carrito de compras

    def empty_cart(request):
        # Obtener el carrito de compras del usuario actual
        shopping_cart = ShoppingCart.objects.get(user=request.user)

        # Obtener los productos
        products = ShoppingCartProduct.objects.filter(cart= shopping_cart)

        # Eliminar los productos del carrito
        products.all().delete()
        shopping_cart.delete()

        return redirect('shop:cart')  # Redirigir a la página del carrito de compras

    def purchase(request):
        # User
        user = request.user

        # Obtener el carrito de compras del usuario actual
        cart = ShoppingCart.objects.get(user=user, is_active=True)

        # Crear una nueva orden de compra.
        with transaction.atomic():
            # Calcular los valores de subtotal, impuestos y total
            subtotal = Decimal('0.00')
            taxes = Decimal('0.00')
            total = Decimal('0.00')

            cart_products = ShoppingCartProduct.objects.filter(cart=cart)

            for cart_product in cart_products:
                subtotal += cart_product.product.price * cart_product.amount

            taxes = subtotal * Decimal('0.19')
            total = subtotal + taxes

            # Obtener la dirección del usuario.
            address = Contact.objects.get(user=user)

            # Método de pago predefinido.
            payment_method = PaymentMethod.objects.get(pk=1)

            try:
                order = PurchaseOrder.objects.get(shopping_cart=cart)
            except:
                # Crear la orden de compra
                order = PurchaseOrder.objects.create(
                    user=user,
                    shopping_cart=cart,
                    shipping_address=address,
                    subtotal=subtotal,
                    taxes=taxes,
                    total=total,
                    payment_method=payment_method,
                    status='P'  # Estado inicial: En proceso
                )

            # Obtener los productos del carrito
            cart_products = ShoppingCartProduct.objects.filter(cart=cart)

            # Guardar cada producto del carrito en la tabla OrderProduct
            for cart_product in cart_products:
                OrderProduct.objects.create(
                    product=cart_product.product,
                    order=order,
                    amount=cart_product.amount
                )

            # Vaciar el carrito de compras
            # cart.is_active = False
            # cart.save()
        return redirect('shop:bill')



class FacturaPDF(View):
    def get(self, request, *args, **kwargs):
        # Obtener el usuario autenticado
        user = request.user

        # Obtener el carrito del usuario
        shopping_cart = ShoppingCart.objects.get(user=user, is_active=True)

        # Obtener los productos en el carrito y calcular el total del valor de la compra
        products = []
        total_price = 0
        total_discount = 0
        cart_products = ShoppingCartProduct.objects.filter(cart=shopping_cart)
        product_instances = {}
        for cart_product in cart_products:
            product = cart_product.product
            if product in product_instances:
                product_instances[product] += cart_product.amount
            else:
                product_instances[product] = cart_product.amount
            total_price += product.price * cart_product.amount

        # Crear una lista de productos únicos con la cantidad de unidades, precio con descuento y subtotal
        for product, amount in product_instances.items():
            discount_price = product.price
            if product.discounts.exists():
                discount = product.discounts.first()
                discount_price -= discount.discount_value
                total_discount += discount.discount_value*amount
            subtotal = discount_price * amount
            products.append({
                'product': product,
                'amount': amount,
                'subtotal': subtotal,
                'price_with_discount': discount_price
            })

        order = shopping_cart.purchaseorder

        data = {
            'order': order,
            'products': products,
            'total_price': total_price,
            'total_discount': total_discount,
            'products_cart_count': len(products)
        }
        pdf = render_to_pdf('shop/bills/bill.html', data)
        return HttpResponse(pdf, content_type='application/pdf')

apps/shop/views/ContactUs.py
from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.views import View
from apps.shop.models import ShoppingCartProduct, ShoppingCart




class ContactUs(View):
    """
    Página "Contáctenos".
    """

    def get(self, request):
        """
        Muestra el formulario de contacto.
        """
        # User
        user = request.user

        if user.is_authenticated:
            # Obtener el carrito del usuario
            try:
                shopping_cart = ShoppingCart.objects.get(user=user, is_active=True)
            except ShoppingCart.DoesNotExist:
                shopping_cart = None
            
            # Obtener la cantidad de productos en el carrito
            if shopping_cart:
                product_count = ShoppingCartProduct.objects.filter(cart=shopping_cart).count()
            else:
                product_count = 0
        else:
            product_count = None

        context = {
            'user' : user,
            'products_cart_count': product_count,
            'path' : request.path
        }
        return render(request, 'shop/contact_us.html', context)


    def post(self, request):
        """
        Envia un mensaje del usuario al correo de la empresa.
        (la dirección de correo está definida en config/.env).
        """
        # Obtenemos los datos del formulario.
        full_name = request.POST['full_name']
        phone = request.POST.get('phone', 'No proporcionado')
        email = request.POST['email']
        message = request.POST['message']

        # Enviamos el email.
        from_email = settings.EMAIL_HOST_USER
        to_list = [settings.EMAIL_HOST_USER]
        subject = 'Mensaje enviado desde el sitio web'
        message = f'Nombre: {full_name}\nEmail: {email}\nTeléfono: {phone}\nMensaje: {message}'

        send_mail(subject, message, from_email, to_list, fail_silently=False)

        # Redirigimos al usuario de nuevo a la vista de contacto.
        messages.success(request, '¡Tu mensaje ha sido enviado!')
        return redirect('shop:contact-us')

apps/shop/views/Discounts.py
from django.views import View
from django.shortcuts import render
from django.db.models import Max, Sum, Avg, Count, F, FloatField
from django.db.models.functions import Cast
from apps.shop.models import ProductDiscount, Category, Brand, ShoppingCartProduct, ShoppingCart

class Discounts(View):

    def get(self, request):

        # User
        user = request.user

        # Obtener todos los productos
        products = ProductDiscount.objects.prefetch_related(
            'product__photos'
            ).select_related(
            'product'
            ).annotate(
            average_rating=Avg('product__reviews__rating'),
            review_count=Count('product__reviews')
            ).filter(
            product__is_active=True
            ).order_by(
            '-product__created_at'
            )

        # Obtener las categorías y marcas para los filtros
        categories = Category.objects.all()
        brands = Brand.objects.all()

        # Obtener los parámetros de filtro de la URL
        category_id = request.GET.get('category')
        brand_id = request.GET.get('brand')
        min_price = request.GET.get('min_price')
        max_price = request.GET.get('max_price')

        # Aplicar filtros si están presentes en la URL
        if category_id:
            products = products.filter(product__category_id=category_id)
        if brand_id:
            products = products.filter(product__brand_id=brand_id)
        if min_price:
            products = products.annotate(min_price_discounted=Cast(F('product__price') - F('discount_value'), output_field=FloatField()))
            products = products.filter(min_price_discounted__gte=min_price)
        if max_price:
            products = products.annotate(max_price_discounted=Cast(F('product__price') - F('discount_value'), output_field=FloatField()))
            products = products.filter(max_price_discounted__lte=max_price)

        if user.is_authenticated:
            # Obtener el carrito del usuario
            try:
                shopping_cart = ShoppingCart.objects.get(user=user, is_active=True)
            except ShoppingCart.DoesNotExist:
                shopping_cart = None
            
            # Obtener la cantidad de productos en el carrito
            if shopping_cart:
                product_count = ShoppingCartProduct.objects.filter(cart=shopping_cart).count()
            else:
                product_count = 0
        else:
            product_count = None

        context = {
            'products': products,
            'categories': categories,
            'brands': brands,
            'selected_category': int(category_id) if category_id else None,
            'selected_brand': int(brand_id) if brand_id else None,
            'min_price': min_price,
            'max_price': max_price,
            'products_cart_count': product_count,
            'path': request.path
        }

        return render(request, 'shop/discounts_list.html', context)

templates/shop/detail/detail.html
{% extends "../../base.html" %}


{% load static %}
{% load humanize %}


{% block title %}{{ product.name }} {{ block.super }} {% endblock %}


{% block content %}
    <div class="container">

        <!-- Sección de detalles -->
        <div class="row mt-5 d-flex align-items-center">

            <!-- Lista de miniaturas de las fotografías del producto -->
            {% if photos %}
                <div class="col-lg-1 d-none d-xl-block">
                    <ul class="list-group">
                        {% for photo in photos %}
                            <li class="list-group-item product-list">
                                <img src="../../media/{{ photo.photo }}" class="img-fluid rounded" onclick="changeCarouselSlide( '{{ forloop.counter0 }}' )" alt="Product photo">
                            </li>
                        {% endfor %}
                    </ul>
                </div>

                <!-- Carrusel con la imagen activa -->
                <div class="col-md-6 col-lg-4 rounded" style="border: 1px solid rgba(0, 0, 0, 0.125);">
                    <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
                        <ol class="carousel-indicators product" style="filter:invert(100%);">
                            {% for photo in photos %}
                                <li data-bs-target="#myCarousel" data-bs-slide-to="{{ forloop.counter0 }}" {% if forloop.first %} class="active" {% endif %}></li>
                            {% endfor %}
                        </ol>
                        <div class="carousel-inner text-center product">
                            {% for photo in photos %}
                                <div class="carousel-item {% if forloop.first %}active{% endif %}">
                                    <img src="../../media/{{ photo.photo }}" class="d-block w-100" alt="product {{ forloop.counter }}">
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% else %}
                <div class="col-md-1 d-none d-xl-block"></div>
                <div class="col-md-4 d-none d-xl-block">
                    <img src="{% static 'img/no_image_available.jpg' %}" class="img-fluid rounded d-block w-100" alt="No image available">
                </div>
            {% endif %}

            <div class="col-md-1 d-none d-lg-block"></div>

            <!-- Información del producto -->
            <div class="col-md-6 col-lg-5 col-xl-4 align-self-start">
                <div class="text-muted fw-light mt-5 mt-md-0">
                    {{ product.category.name }} &nbsp; | &nbsp; {{ product.brand.name }}
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                    {% if product.stock < 15 %}
                        <span class="text-danger">{{ product.stock }} disponibles</span>
                    {% endif %}
                </div>

                <h1 class="fs-3 fw-bold">{{ product.name }}</h1>

                <div class="mt-3">
                    {% if discount_percentage %}
                        <div class="d-flex align-items-center">
                            <span class="text-decoration-line-through text-muted">
                                ${{ product.price|intcomma }}
                            </span>
                            &nbsp;&nbsp;
                            <span class="badge rounded-pill bg-warning text-dark">
                                {{ discount_percentage }}% de descuento
                            </span>
                        </div>
                    {% endif %}

                    <div class="text-primary fs-5 fw-bold">
                        ${{ total|intcomma }}
                    </div>
                </div>

                <hr>

                <div>{{ product.description }}</div>

                <div class="mt-5">
                    <form id="form" action="{% url 'shop:detail' product.pk %}" method="POST">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <input type="number" class="form-control" id="quantity" name="quantity" value="1" style="flex: 0 1 100px;" min="1" oninput="validateQuantity(this)" required>
                            <button type="submit" class="btn btn-outline-primary">
                                <i class="fas fa-shopping-cart"></i>
                                <span>&nbsp; Añadir al carrito</span>
                            </button>
                            {% include 'includes/addi_bar.html' %}
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- Sección de reseñas -->
        <div class="row text-left mt-5">
            <h1 class="fs-5 fw-bold">
                Opiniones del producto

                {% if not has_bought %}
                    <i class="far fa-question-circle" data-bs-toggle="tooltip" data-bs-placement="right" title="Compra antes de opinar."></i>
                {% endif %}

                {% if has_reviewed %}
                    <i class="far fa-question-circle" data-bs-toggle="tooltip" data-bs-placement="right" title="Ya reseñaste este producto."></i>
                {% endif %}
            </h1>

            {% if has_bought and not has_reviewed %}
                <a href="#" data-bs-toggle="modal" data-bs-target="#escribirOpinion">Deja una opinión.</a>

                {% include './modal_escribir_resena.html' %}
            {% endif %}
        </div>

        <div class="row">
            {% if reviews %}
                <div class="col-md-6 col-lg-4 col-xl-3 px-4 px-lg-2 text-left mt-5">
                    <div class="d-flex align-items-center">
                        <div class="fs-1 fw-bold text-danger pe-5">{{ average_rating }}</div>
                        <div>
                            {% for i in '12345'|make_list %}
                                {% if i|add:'0' <= average_rating %}
                                    <i class="fas fa-star text-warning"></i>
                                {% else %}
                                    <i class="far fa-star text-warning"></i>
                                {% endif %}
                            {% endfor %}
                            <br>
                            {{ total_reviews }} calificaciones
                        </div>
                    </div>
                    <div class="mt-3">
                        {% for key, value in rating_counts.items %}
                            <div class="d-flex align-items-center justify-content-between">
                                <progress id="rating_{{ key }}" value="{{ value }}" max="{{ total_reviews }}">{{ value }}</progress>
                                <label class="text-muted" for="rating_{{ key }}">{{ value }} &nbsp; <i class="fas fa-star text-dark"></i></label><br>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}

            <div class="col-md-6 col-xl-7 text-left mt-4 m-xl-4">
                {% for review in reviews|slice:reviews_displayed %}
                    <div class="border rounded p-3 mb-1 mt-3">
                        <div class="d-flex justify-content-between">
                            <div class="mb-1">
                                {% for i in '12345'|make_list %}
                                    {% if i|add:'0' <= review.rating %}
                                        <i class="fas fa-star text-warning"></i>
                                    {% else %}
                                        <i class="far fa-star text-warning"></i>
                                    {% endif %}
                                {% endfor %}
                            </div>
                            <div class="text-muted">{{ review.created_at|naturaltime }}</div>
                        </div>
                        {{ review.comment }}
                    </div>
                {% empty %}
                    <p class="text-muted fst-italic">
                        Este producto aún no tiene reseñas.
                    </p>
                {% endfor %}

                {% if reviews|length > reviews_displayed %}
                    <div class="p-3 mb-1 mt-3">
                        <a href="#" data-bs-toggle="modal" data-bs-target="#myModal">Ver todas las opiniones.</a>
                    </div>

                    {% include './modal_ver_resenas.html' %}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}


{% block js %}
    <script>
        // Cambia el slide del carousel al hacer clic en una foto de la lista.
        function changeCarouselSlide(index) {
            let i = parseInt(index)
            $('#myCarousel').carousel(i);
        }


        // Valida que la cantidad ingresada al carrito de compra sea mayor o igual a 1.
        function validateQuantity(input) {
            if (input.value < 1) {
                input.value = 1;
            }
        }


        // Habilita el uso de tooltips.
        $(document).ready(function(){
            $('[data-bs-toggle="tooltip"]').tooltip();
        });


        // Permite que el usuario califique dinámicamente el producto al hacer la reseña.
        document.addEventListener('DOMContentLoaded', function() {
            const stars = document.querySelectorAll('.my-star');
            const ratingInput = document.getElementById('rating');

            stars.forEach(star => {
                star.addEventListener('click', () => {
                    const index = star.getAttribute('data-index');
                    ratingInput.value = parseInt(index) + 1;
                    markStars(index);
                });
            });

            function markStars(index) {
                stars.forEach((star, i) => {
                    if (i <= index) {
                        star.classList.remove('far');
                        star.classList.add('fas');
                    } else {
                        star.classList.remove('fas');
                        star.classList.add('far');
                    }
                });
            }
        });
    </script>
{% endblock %}

templates/shop/detail/modal_escribir_resena.html
<div id="escribirOpinion" class="modal fade" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title fw-bold">¿Qué te pareció nuestro producto {{ product.name }}?</h6>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></butto>
            </div>

            <form id="review_form" action="{% url 'shop:make-review' product.pk %}" method="POST">
                <div class="modal-body">
                    {% csrf_token %}
                    <textarea class="form-control" id="comment" name="comment" rows="5" required></textarea>

                    <div class="px-2 py-3">
                        <input type="hidden" id="rating" name="rating">
                        <span>Califica el producto: </span>
                        {% for i in '12345'|make_list %}
                            <i class="far fa-star text-warning my-star" data-index="{{ forloop.counter0 }}"></i>
                        {% endfor %}
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-outline-primary" id="submit-btn">
                        Dejar reseña
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

templates/shop/detail/modal_ver_resenas.html
{% load humanize %}

<div id="myModal" class="modal fade" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title fw-bold">¿Qué opinan nuestros clientes del producto {{ product.name }}?</h6>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></butto>
            </div>
            <div class="modal-body">
                {% for review in reviews %}
                    <div class="border rounded p-3 mb-1 mt-3">
                        <div class="d-flex justify-content-between">
                            <div class="mb-1">
                                {% for i in '12345'|make_list %}
                                    {% if i|add:'0' <= review.rating %}
                                        <i class="fas fa-star text-warning"></i>
                                    {% else %}
                                        <i class="far fa-star text-warning"></i>
                                    {% endif %}
                                {% endfor %}
                            </div>
                            <div class="text-muted">{{ review.created_at|naturaltime }}</div>
                        </div>
                        {{ review.comment }}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>